# Report Routes
# backend/app/routes/report.py
from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from app.models.schemas import ReportRequest
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.colors import HexColor, white
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
    HRFlowable, Table, TableStyle)
from reportlab.lib.units import cm
import io

router = APIRouter()

def color(hex_str):
    return HexColor(hex_str)

@router.post("/generate")
async def generate_report(data: ReportRequest):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=2*cm, bottomMargin=2*cm,
        leftMargin=2.5*cm, rightMargin=2.5*cm
    )

    # Styles
    def style(name, **kw):
        return ParagraphStyle(name, **kw)

    title_s    = style("T", fontSize=26, textColor=color("#34d399"), fontName="Helvetica-Bold", spaceAfter=4)
    subtitle_s = style("S", fontSize=12, textColor=color("#94a3b8"), spaceAfter=20)
    head_s     = style("H", fontSize=14, textColor=color("#34d399"), fontName="Helvetica-Bold", spaceBefore=16, spaceAfter=6)
    label_s    = style("L", fontSize=9,  textColor=color("#64748b"), spaceAfter=2)
    value_s    = style("V", fontSize=14, textColor=color("#f1f5f9"), fontName="Helvetica-Bold", spaceAfter=8)
    body_s     = style("B", fontSize=11, textColor=color("#cbd5e1"), spaceAfter=6, leading=18)
    footer_s   = style("F", fontSize=9,  textColor=color("#334155"), alignment=1)

    story = []

    # Header
    story.append(Paragraph("HealthPro AI", title_s))
    story.append(Paragraph("Personal Health Assessment Report", subtitle_s))
    story.append(HRFlowable(width="100%", thickness=1, color=color("#1e293b"), spaceAfter=16))

    # Patient Info Table
    story.append(Paragraph("Patient Information", head_s))
    table_data = [
        ["Full Name", data.name, "Report Date", data.date],
        ["Body Weight", f"{data.weight} kg", "Height", f"{data.height:.2f} m"],
        ["BMI Score", str(data.bmi), "BMI Category", data.category],
    ]
    t = Table(table_data, colWidths=[4*cm, 6*cm, 4*cm, 6*cm])
    t.setStyle(TableStyle([
        ("BACKGROUND",   (0,0), (-1,-1), color("#0d1a2b")),
        ("TEXTCOLOR",    (0,0), (-1,-1), color("#94a3b8")),
        ("TEXTCOLOR",    (1,0), (1,-1), color("#f1f5f9")),
        ("TEXTCOLOR",    (3,0), (3,-1), color("#f1f5f9")),
        ("FONTNAME",     (0,0), (-1,-1), "Helvetica"),
        ("FONTSIZE",     (0,0), (-1,-1), 10),
        ("FONTNAME",     (1,0), (1,-1), "Helvetica-Bold"),
        ("FONTNAME",     (3,0), (3,-1), "Helvetica-Bold"),
        ("ROWBACKGROUNDS",(0,0),(-1,-1),[color("#0d1a2b"),color("#0f1f2e")]),
        ("GRID",         (0,0), (-1,-1), 0.5, color("#1e293b")),
        ("PADDING",      (0,0), (-1,-1), 10),
        ("TOPPADDING",   (0,0), (-1,-1), 8),
        ("BOTTOMPADDING",(0,0), (-1,-1), 8),
    ]))
    story.append(t)
    story.append(Spacer(1, 12))

    # AI Recommendations
    story.append(HRFlowable(width="100%", thickness=1, color=color("#1e293b"), spaceBefore=4, spaceAfter=4))
    story.append(Paragraph("AI Health Recommendations", head_s))
    for line in data.advice.split("\n"):
        if line.strip():
            story.append(Paragraph(line.strip(), body_s))

    story.append(Spacer(1, 30))
    story.append(HRFlowable(width="100%", thickness=0.5, color=color("#1e293b")))
    story.append(Spacer(1, 8))
    story.append(Paragraph(
        f"Generated by HealthPro AI on {data.date} | Made by Abhinash Kumar | This report is for informational purposes only.",
        footer_s
    ))

    doc.build(story)
    buffer.seek(0)

    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename=HealthPro-{data.name.replace(' ','-')}.pdf"}
    )